partial closure of landing page items
RMI-Climate-Intelligence/oci pull request #47
Opened 2021-12-02 18:59 UTC by drewbo

Partially addresses some of the items in https://github.com/RMI-Climate-Intelligence/oci/issues/45; could use a checklist and design review (since the addition of new content throws off some rows). I'll also follow up with RMI on additional content

2021-12-03 15:52 UTC, danielfdsilva requested changes

2021-12-03 15:52 UTC, danielfdsilva commented on app/assets/styles/_collecticons.scss
> +/* ==========================================================================
This file is no longer needed/used and should be removed

2021-12-06 16:28 UTC, drewbo commented
@hanbyul-here yeah this definitely needs some thinking but I wasn't sure how to arrange better; I had to add one more partner which made a new line + the addition of contributing partners

2021-12-06 21:14 UTC, hanbyul-here commented
Yeah, maybe we can bring 'the oci+ researchers~' part down to the bottom (so it becomes a separate row.)? I will handle once it is merged.

2021-12-06 21:14 UTC, hanbyul-here approved these changes

2021-12-09 12:45 UTC, danielfdsilva approved these changes

2021-12-09 14:56 UTC, merged