Case study page
RMI-Climate-Intelligence/oci pull request #48
Opened 2021-12-03 16:53 UTC by hanbyul-here

2021-12-21 21:50 UTC, hanbyul-here commented on app/assets/scripts/components/case-studies/each-case/index.js
> +    /* TO DO : how to redirect to 404? */
@danielfdsilva  I want to validate the url, and redirect the page to 404 if there is no matching case. Can I pick your brain about what would be the best way to handle this?

2021-12-22 11:28 UTC, danielfdsilva commented on app/assets/scripts/components/case-studies/each-case/index.js
> +    /* TO DO : how to redirect to 404? */
Given that this component is a "view" I'd render the `<UhOh />` component directly (`return <UhOh />`). In this way you get the keep the invalid url in the address bar and the user understands what happened.
Another alternative your be to redirect to the 404 page, but you lose context.

2021-12-22 14:16 UTC, hanbyul-here commented on app/assets/scripts/components/case-studies/each-case/index.js
> +    /* TO DO : how to redirect to 404? */
Oh yes, makes sense! Thanks 🤩 !

2022-01-13 11:51 UTC, danielfdsilva requested changes

2022-01-13 11:51 UTC, danielfdsilva commented on app/assets/scripts/components/scenarios/index.js
> +const CaseStudyEntryInner = styled.a`
This should extend `Link`. If you use a `a` element, the router won't be used and the whole site will be loaded again

2022-01-13 20:18 UTC, hanbyul-here commented on app/assets/scripts/components/supply-chain/infographics/index.js
> +  const { modelValue } = useFetchModel(modelId, !useGwp);
I'd like to pick your brain about one thing. 
so on supply chain page, we don't use model data, only use the part of info. but on scenario page, model data is needed. I ended up with moving this conditional data request logic to `useFetchModel` hook.  (https://github.com/RMI-Climate-Intelligence/oci/pull/48/files#diff-550ec06db6c6922616bf20b4d5c2d8a3bc48f7127808b0ca3cf47872b0601e1dR14) I am not sure about this decision, since this hook's entire purpose is to fetch/cache data.. 🤔  Can I ask if you would have dealt this problem differently?

2022-01-14 10:57 UTC, danielfdsilva commented on app/assets/scripts/components/supply-chain/infographics/index.js
> +  const { modelValue } = useFetchModel(modelId, !useGwp);
hmm. interesting problem. In this case I think I'd have extracted that hook call to the parent and passed the `modelValue` as a prop.
The result would be a leaner component where you don't need to dig into the code to understand the flow.
Now, if pressed for time, this solution works fine 👍

2022-01-14 17:12 UTC, hanbyul-here commented
Thanks for telling me the convention. I rearranged files to follow it @danielfdsilva !

2022-01-18 16:46 UTC, danielfdsilva approved these changes

2022-01-18 18:47 UTC, hanbyul-here commented on app/assets/scripts/components/supply-chain/infographics/index.js
> +  const { modelValue } = useFetchModel(modelId, !useGwp);
I will keep this for now but yeah, moving this logic to more up will be better for readability. Thanks for offering your insight!

2022-01-18 19:04 UTC, merged